from pathlib import Path

path = Path('frontend/tests/frontend-audit-regressions.spec.ts')
text = path.read_text(encoding='utf-8')
old = """  it('keeps声音详情的工程身份和原始状态码下沉到技术详情', async () => {\n    const source = await readFile(\n      new URL('../src/features/voice-plaza/pages/VoicePlazaPage/components/ContentDetailDrawer.vue', import.meta.url),\n      'utf8',\n    )\n    const technicalIndex = source.indexOf('<summary>技术详情</summary>')\n\n    expect(technicalIndex).toBeGreaterThan(-1)\n    expect(source).not.toContain('Content ID: {{ item.id }}')\n    expect(source.indexOf('<dt>Content ID</dt>')).toBeGreaterThan(technicalIndex)\n    expect(source.indexOf('<dt>外部内容 ID</dt>')).toBeGreaterThan(technicalIndex)\n    expect(source).toContain('<h4>内容可用状态</h4>')\n    expect(source).not.toContain('{{ item.availability.status }} · {{ item.availability.reason_code }} · {{ item.availability.evidence_kind }}')\n    expect(source).toContain(\"sourceLabel(item.source.provider_name)\")\n    expect(source).toContain(\"contentTypeLabel(item.content_type)\")\n  })\n"""
new = """  it('将声音详情的工程身份和原始状态码下沉到技术详情', async () => {\n    const source = await readFile(\n      new URL('../src/features/voice-plaza/pages/VoicePlazaPage/components/ContentDetailDrawer.vue', import.meta.url),\n      'utf8',\n    )\n    const technicalIndex = source.indexOf('<summary>技术详情</summary>')\n    const rawAvailabilityIndex = source.indexOf('{{ item.availability.status }} · {{ item.availability.reason_code }} · {{ item.availability.evidence_kind }}')\n\n    expect(technicalIndex).toBeGreaterThan(-1)\n    expect(source).not.toContain('Content ID: {{ item.id }}')\n    expect(source.indexOf('<dt>Content ID</dt>')).toBeGreaterThan(technicalIndex)\n    expect(source.indexOf('<dt>外部内容 ID</dt>')).toBeGreaterThan(technicalIndex)\n    expect(source).toContain('<h4>内容可用状态</h4>')\n    expect(rawAvailabilityIndex).toBeGreaterThan(technicalIndex)\n    expect(source).toContain(\"sourceLabel(item.source.provider_name)\")\n    expect(source).toContain(\"contentTypeLabel(item.content_type)\")\n  })\n"""
if text.count(old) != 1:
    raise RuntimeError(f'expected one target block, found {text.count(old)}')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
