"""Stage 6 Content/Comment Current 与 History 表。"""

from sqlalchemy import (
    CheckConstraint,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Table,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB

from aima_ugc.platform.database.metadata import metadata

accounts_table = Table(
    "accounts",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("platform", Text(), nullable=False),
    Column("external_account_id", Text(), nullable=False),
    Column("display_name", Text()),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("platform", "external_account_id"),
    info={"owner": "content"},
)

contents_table = Table(
    "contents",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("platform", Text(), nullable=False),
    Column("external_content_id", Text(), nullable=False),
    Column("content_type", Text(), nullable=False),
    Column("title", Text()),
    Column("text", Text()),
    Column("canonical_url", Text()),
    Column("share_url", Text()),
    Column("author_account_id", Uuid(), ForeignKey("accounts.id")),
    Column("published_at", DateTime(timezone=True)),
    Column("source_updated_at", DateTime(timezone=True)),
    Column("status", Text()),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    Column("current_version", Integer(), nullable=False),
    Column("current_like_count", Integer()),
    Column("current_comment_count", Integer()),
    Column("current_share_count", Integer()),
    Column("current_repost_count", Integer()),
    Column("current_favorite_count", Integer()),
    Column("current_view_count", Integer()),
    Column("current_play_count", Integer()),
    Column("current_danmaku_count", Integer()),
    Column("current_coin_count", Integer()),
    Column("current_download_count", Integer()),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("platform", "external_content_id"),
    CheckConstraint("current_version >= 1", name="current_version_positive"),
    info={"owner": "content"},
)

content_versions_table = Table(
    "content_versions",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("content_id", Uuid(), ForeignKey("contents.id"), nullable=False),
    Column("version_no", Integer(), nullable=False),
    Column("content_type", Text(), nullable=False),
    Column("title", Text()),
    Column("text", Text()),
    Column("canonical_url", Text()),
    Column("share_url", Text()),
    Column("author_snapshot", JSONB()),
    Column("published_at", DateTime(timezone=True)),
    Column("source_updated_at", DateTime(timezone=True)),
    Column("status", Text()),
    Column("provider_attempt_id", Uuid(), ForeignKey("provider_request_attempts.id"), nullable=False),
    Column("raw_artifact_id", Uuid(), ForeignKey("artifacts.id"), nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("content_id", "version_no"),
    CheckConstraint("version_no >= 1", name="version_no_positive"),
    info={"owner": "content"},
)

content_metric_observations_table = Table(
    "content_metric_observations",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("content_id", Uuid(), ForeignKey("contents.id"), nullable=False),
    Column("provider_attempt_id", Uuid(), ForeignKey("provider_request_attempts.id"), nullable=False),
    Column("raw_artifact_id", Uuid(), ForeignKey("artifacts.id"), nullable=False),
    Column("reason", Text(), nullable=False),
    Column("business_date", Date(), nullable=False),
    Column("observation_key", Text(), nullable=False),
    Column("like_count", Integer()),
    Column("comment_count", Integer()),
    Column("share_count", Integer()),
    Column("repost_count", Integer()),
    Column("favorite_count", Integer()),
    Column("view_count", Integer()),
    Column("play_count", Integer()),
    Column("danmaku_count", Integer()),
    Column("coin_count", Integer()),
    Column("download_count", Integer()),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("content_id", "observation_key"),
    CheckConstraint(
        "reason in ('initial','changed','daily_checkpoint')",
        name="reason_allowed",
    ),
    info={"owner": "content"},
)

comments_table = Table(
    "comments",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("content_id", Uuid(), ForeignKey("contents.id"), nullable=False),
    Column("external_comment_id", Text(), nullable=False),
    Column("root_comment_id", Text()),
    Column("parent_comment_id", Text()),
    Column("author_account_id", Uuid(), ForeignKey("accounts.id")),
    Column("text", Text()),
    Column("published_at", DateTime(timezone=True)),
    Column("source_updated_at", DateTime(timezone=True)),
    Column("status", Text()),
    Column("is_by_content_author", Integer()),
    Column("first_seen_at", DateTime(timezone=True), nullable=False),
    Column("last_seen_at", DateTime(timezone=True), nullable=False),
    Column("current_like_count", Integer()),
    Column("current_reply_count", Integer()),
    Column("current_version", Integer(), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("content_id", "external_comment_id"),
    CheckConstraint("current_version >= 1", name="current_version_positive"),
    info={"owner": "content"},
)

comment_versions_table = Table(
    "comment_versions",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("comment_id", Uuid(), ForeignKey("comments.id"), nullable=False),
    Column("version_no", Integer(), nullable=False),
    Column("root_comment_id", Text()),
    Column("parent_comment_id", Text()),
    Column("text", Text()),
    Column("author_snapshot", JSONB()),
    Column("published_at", DateTime(timezone=True)),
    Column("source_updated_at", DateTime(timezone=True)),
    Column("status", Text()),
    Column("is_by_content_author", Integer()),
    Column("provider_attempt_id", Uuid(), ForeignKey("provider_request_attempts.id"), nullable=False),
    Column("raw_artifact_id", Uuid(), ForeignKey("artifacts.id"), nullable=False),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("comment_id", "version_no"),
    CheckConstraint("version_no >= 1", name="version_no_positive"),
    info={"owner": "content"},
)

comment_metric_observations_table = Table(
    "comment_metric_observations",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("comment_id", Uuid(), ForeignKey("comments.id"), nullable=False),
    Column("provider_attempt_id", Uuid(), ForeignKey("provider_request_attempts.id"), nullable=False),
    Column("raw_artifact_id", Uuid(), ForeignKey("artifacts.id"), nullable=False),
    Column("reason", Text(), nullable=False),
    Column("business_date", Date(), nullable=False),
    Column("observation_key", Text(), nullable=False),
    Column("like_count", Integer()),
    Column("reply_count", Integer()),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    UniqueConstraint("comment_id", "observation_key"),
    CheckConstraint(
        "reason in ('initial','changed','daily_checkpoint')",
        name="reason_allowed",
    ),
    info={"owner": "content"},
)

comment_coverage_observations_table = Table(
    "comment_coverage_observations",
    metadata,
    Column("id", Uuid(), primary_key=True),
    Column("content_id", Uuid(), ForeignKey("contents.id"), nullable=False),
    Column("provider_attempt_id", Uuid(), ForeignKey("provider_request_attempts.id"), nullable=False),
    Column("raw_artifact_id", Uuid(), ForeignKey("artifacts.id"), nullable=False),
    Column("coverage", Text(), nullable=False),
    Column("reported_total", Integer()),
    Column("collected_count", Integer(), nullable=False, server_default=text("0")),
    Column("observed_at", DateTime(timezone=True), nullable=False),
    CheckConstraint(
        "coverage in ('complete','partial','not_requested','unavailable')",
        name="coverage_allowed",
    ),
    CheckConstraint("collected_count >= 0", name="collected_count_nonnegative"),
    info={"owner": "content"},
)

Index("ix_contents_platform_last_seen", contents_table.c.platform, contents_table.c.last_seen_at)
Index("ix_comments_content_id_last_seen", comments_table.c.content_id, comments_table.c.last_seen_at)
Index(
    "uq_content_metric_daily_checkpoint",
    content_metric_observations_table.c.content_id,
    content_metric_observations_table.c.business_date,
    unique=True,
    postgresql_where=content_metric_observations_table.c.reason == "daily_checkpoint",
)
Index(
    "uq_comment_metric_daily_checkpoint",
    comment_metric_observations_table.c.comment_id,
    comment_metric_observations_table.c.business_date,
    unique=True,
    postgresql_where=comment_metric_observations_table.c.reason == "daily_checkpoint",
)
