"""真实 Docker PostgreSQL 恢复；只创建本测试拥有的容器/数据库，小型合成快照不依赖LFS。"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import shutil
import sys
import tarfile
import time
import uuid
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]


def load_script(name: str):
    """沿用仓库脚本加载模式。"""
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts/dev" / f"{name}.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


load_script("local_runtime")
snapshot = load_script("recent_snapshot")
seed = load_script("seed_data")


@pytest.fixture(scope="module")
def pg_container(tmp_path_factory):
    """独立临时容器，既不复用固定开发库也不接触CI服务库。"""
    if not shutil.which("docker"):
        pytest.fail("真实开发快照恢复测试需要 Docker")
    name = "aima-seed-test-" + uuid.uuid4().hex[:12]
    password_file = tmp_path_factory.mktemp("seed-pg") / "password"
    password_file.write_text("isolated-seed-test-password", encoding="utf-8")
    container_id = (
        seed.docker(
            [
                "run",
                "-d",
                "--name",
                name,
                "--label",
                "aima.test=dev-seed-716",
                "-e",
                "POSTGRES_USER=aima_seed",
                "-e",
                "POSTGRES_DB=source",
                "-e",
                "POSTGRES_PASSWORD=isolated-seed-test-password",
                "-p",
                "127.0.0.1::5432",
                "postgres:18.4",
            ],
            phase="创建隔离测试数据库",
        )
        .decode()
        .strip()
    )
    try:
        value = json.loads(seed.docker(["inspect", container_id], phase="读取隔离容器"))[0]
        port = int(value["NetworkSettings"]["Ports"]["5432/tcp"][0]["HostPort"])
        target = seed.DatabaseTarget(
            name, "source", "aima_seed", "127.0.0.1", port, password_file, container_id
        )
        for _ in range(60):
            try:
                target.psql("SELECT 1;")
                break
            except snapshot.SnapshotError:
                time.sleep(0.25)
        else:
            pytest.fail("隔离 PostgreSQL 未 ready")
        yield target
    finally:
        value = json.loads(seed.docker(["inspect", container_id], phase="确认本测试容器归属"))[0]
        assert value["Name"] == "/" + name
        assert value["Config"]["Labels"]["aima.test"] == "dev-seed-716"
        seed.docker(["rm", "-f", "-v", container_id], phase="清理本测试容器")


@pytest.fixture(scope="module")
def synthetic_archive(pg_container, tmp_path_factory):
    """由真实 pg_dump/COPY 产生原格式Fixture，包含回复、标签、人工结果与Artifact。"""
    target = pg_container
    special = {
        "alembic_version": "version_num text PRIMARY KEY",
        "contents": "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text",
        "comments": "id bigint PRIMARY KEY, content_id bigint, parent_id bigint, body text",
        "analysis_content_results": "id bigint PRIMARY KEY, content_id bigint, sentiment text",
        "analysis_content_manual_overrides": "id bigint PRIMARY KEY, result_id bigint, "
        "sentiment text",
        "artifacts": "id bigint PRIMARY KEY, storage_backend text, storage_status text, "
        "storage_key text, sha256 text, byte_size bigint",
        "jobs": "id bigint PRIMARY KEY, status text, lease_owner text, lease_token text, "
        "lease_expires_at timestamptz, "
        "finished_at timestamptz, error_code text, updated_at timestamptz",
        "collection_runs": "id bigint PRIMARY KEY, status text, finished_at timestamptz",
        "collection_plans": "id bigint PRIMARY KEY, enabled boolean, updated_at timestamptz",
        "provider_configs": "id bigint PRIMARY KEY, enabled boolean, is_default boolean, "
        "updated_at timestamptz",
    }
    names = snapshot.CORE | special.keys()
    for name in sorted(names):
        target.psql(
            f"CREATE TABLE {snapshot.quote(name)} ({special.get(name, 'id bigint PRIMARY KEY')});"
        )
    blob = b'{"fixture":"raw"}'
    target.psql(
        "ALTER TABLE comments ADD FOREIGN KEY(content_id) REFERENCES contents(id);"
        "ALTER TABLE comments ADD FOREIGN KEY(parent_id) REFERENCES comments(id);"
        "ALTER TABLE analysis_content_results ADD FOREIGN KEY(content_id) REFERENCES contents(id);"
        "ALTER TABLE analysis_content_manual_overrides ADD FOREIGN KEY(result_id) "
        "REFERENCES analysis_content_results(id);"
    )
    digest = hashlib.sha256(blob).hexdigest()
    target.psql(
        "INSERT INTO alembic_version VALUES ('20261003_0082');"
        """INSERT INTO contents VALUES (42, E'含引号"与换行\\n正文');"""
        "INSERT INTO comments VALUES (1,42,NULL,'一级'),(2,42,1,'二级回复');"
        "INSERT INTO analysis_content_results VALUES (3,42,'正面');"
        "INSERT INTO analysis_content_manual_overrides VALUES (4,3,'中性');"
        "INSERT INTO jobs VALUES (1,'queued',NULL,NULL,NULL,NULL,NULL,now()),"
        "(2,'running','old','old',now(),NULL,NULL,now()),"
        "(3,'succeeded',NULL,NULL,NULL,now(),NULL,now());"
        "INSERT INTO collection_runs VALUES (1,'running',NULL);"
        "INSERT INTO collection_plans VALUES (1,true,now());"
        "INSERT INTO provider_configs VALUES (1,true,true,now());"
        "INSERT INTO artifacts VALUES (1,'local','stored','raw/fixture.json',"
        f"'{digest}',{len(blob)});"
    )
    meta = json.loads(target.psql(snapshot.metadata_query()))
    folder = tmp_path_factory.mktemp("合成 快照")
    (folder / "data").mkdir()
    (folder / "artifacts/raw").mkdir(parents=True)
    (folder / "artifacts/raw/fixture.json").write_bytes(blob)
    schema = seed.docker(
        [
            "exec",
            target.container,
            "pg_dump",
            "-U",
            target.user,
            "-d",
            target.database,
            "-Fc",
            "--schema-only",
            "--no-owner",
            "--no-acl",
        ],
        phase="生成合成Schema",
    )
    (folder / "schema.dump").write_bytes(schema)
    tables = []
    for table in meta["tables"]:
        file = "data/" + snapshot.selected_name(table["name"]) + ".csv"
        sql = (
            f"COPY public.{snapshot.quote(table['name'])} TO STDOUT WITH (FORMAT csv, NULL '\\N');"
        )
        # Docker字节stdout保留COPY CSV原始换行，不能用strip后字符串回写。
        code = 'exec psql -X -v ON_ERROR_STOP=1 -U "$1" -d "$2" -c "$3"'
        data = seed.docker(
            ["exec", target.container, "sh", "-ec", code, "sh", target.user, target.database, sql],
            phase="生成合成CSV",
        )
        (folder / file).write_bytes(data)
        tables.append(
            {
                **table,
                "file": file,
                "size": len(data),
                "count": int(target.psql(f"SELECT count(*) FROM {snapshot.quote(table['name'])};")),
                "sha256": hashlib.sha256(data).hexdigest(),
            }
        )
    manifest = {
        "format": snapshot.FORMAT,
        "postgres_major": 18,
        "alembic_version": "20261003_0082",
        "tables": tables,
        "foreign_keys": meta["fks"],
        "schema_size": len(schema),
        "schema_sha256": hashlib.sha256(schema).hexdigest(),
        "artifacts": [{"storage_key": "raw/fixture.json", "size": len(blob), "sha256": digest}],
        "missing_artifacts": [],
    }
    (folder / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
    archive = folder / "fixture.tar.gz"
    with tarfile.open(archive, "w:gz") as tar:
        for file in sorted(folder.rglob("*")):
            if file.is_file() and file != archive:
                tar.add(file, arcname=file.relative_to(folder).as_posix(), recursive=False)
    return archive


@pytest.fixture
def workspace(tmp_path, pg_container, synthetic_archive, monkeypatch):
    """每个案例有独立空DB及中文/空格宿主路径，恢复生产函数不Mock数据库。"""
    from dataclasses import replace

    root = tmp_path / "开发 工作区"
    root.mkdir()
    shutil.copy(ROOT / "alembic.ini", root / "alembic.ini")
    shutil.copytree(ROOT / "migrations", root / "migrations")
    archive = root / "devdata/seed/aima_recent30.tar.gz"
    archive.parent.mkdir(parents=True)
    shutil.copy(synthetic_archive, archive)
    db = "restore_" + uuid.uuid4().hex[:12]
    pg_container.psql(f"CREATE DATABASE {snapshot.quote(db)};", database="postgres")
    target = replace(pg_container, database=db)
    monkeypatch.delenv("CI", raising=False)
    monkeypatch.delenv("GITHUB_ACTIONS", raising=False)
    return seed.runtime_paths(root), target


def test_real_restore_then_repeat_and_update(workspace) -> None:
    """真实恢复闭包、回复、AI/人工结论、序列、任务禁用和重复启动不覆写。"""
    paths, target = workspace
    assert "恢复完成" in seed.initialize(paths, target=target)
    assert target.summary() == {"contents": 1, "comments": 2, "analysis_content_results": 1}
    assert target.psql("SELECT parent_id FROM comments WHERE id=2;") == "1"
    assert target.psql("SELECT sentiment FROM analysis_content_results;") == "正面"
    assert target.psql("SELECT sentiment FROM analysis_content_manual_overrides;") == "中性"
    assert target.psql("SELECT count(*) FROM jobs WHERE status IN ('queued','running');") == "0"
    assert target.psql("SELECT status FROM jobs WHERE id=3;") == "succeeded"
    assert target.psql("SELECT enabled OR is_default FROM provider_configs;") == "f"
    assert target.psql("SELECT enabled FROM collection_plans;") == "f"
    assert (paths.data / "artifacts/raw/fixture.json").read_bytes() == b'{"fixture":"raw"}'
    assert (
        target.psql("INSERT INTO contents(title) VALUES('新增') RETURNING id;").splitlines()[0]
        == "43"
    )
    assert "保留" in seed.initialize(paths, target=target)
    archive = paths.root / "devdata/seed/aima_recent30.tar.gz"
    with archive.open("ab") as handle:
        handle.write(b"changed")
    assert "已更新" in seed.initialize(paths, target=target)
    assert target.psql("SELECT count(*) FROM contents;") == "2"


def test_interrupted_restore_keeps_partial_database_and_blocks_skip(workspace, monkeypatch) -> None:
    """文件发布阶段中断后保留库，状态失败且skip不能继续；无自动DROP。"""
    paths, target = workspace

    def fail(*_args):
        """注入DB提交后的文件失败。"""
        raise snapshot.SnapshotError("synthetic file failure")

    monkeypatch.setattr(snapshot, "install_artifacts", fail)
    with pytest.raises(snapshot.SnapshotError):
        seed.initialize(paths, target=target)
    assert target.psql("SELECT count(*) FROM contents;") == "1"
    assert seed.read_state(paths)["status"] == "failed"
    with pytest.raises(snapshot.SnapshotError, match="未完成"):
        seed.initialize(paths, skip=True, target=target)


def test_advisory_lock_and_live_connections_prevent_writes(workspace) -> None:
    """并发恢复/reset共用postgres库锁，API样连接存在时也拒绝恢复。"""
    import psycopg

    paths, target = workspace
    with target.lock():
        with pytest.raises(snapshot.SnapshotError, match="正在进行"):
            seed.initialize(paths, target=target)
    with psycopg.connect(
        host=target.host,
        port=target.port,
        user=target.user,
        password=target.password_file.read_text(),
        dbname=target.database,
    ):
        with pytest.raises(snapshot.SnapshotError, match="仍有连接"):
            seed.initialize(paths, target=target)
    assert target.empty()
    assert seed.read_state(paths) is None


def test_internal_autovacuum_does_not_block_but_client_connections_do(workspace) -> None:
    """真实后台维护不能冒充业务连接，仍拒绝另一个客户端连接。"""
    import psycopg

    _, target = workspace
    target.psql("ALTER SYSTEM SET autovacuum_naptime='1s';")
    target.psql("SELECT pg_reload_conf();")
    target.psql(
        "CREATE TABLE seed_autovacuum_probe(payload text) WITH "
        "(autovacuum_vacuum_insert_threshold=1,autovacuum_vacuum_insert_scale_factor=0,"
        "autovacuum_analyze_threshold=1,autovacuum_analyze_scale_factor=0,"
        "autovacuum_vacuum_cost_delay=20,autovacuum_vacuum_cost_limit=1); "
        "ALTER TABLE seed_autovacuum_probe ALTER COLUMN payload SET STORAGE PLAIN; "
        "INSERT INTO seed_autovacuum_probe SELECT repeat('a',2000) FROM generate_series(1,10000);"
    )
    worker = ""
    try:
        for _ in range(80):
            worker = target.psql(
                "SELECT pid FROM pg_stat_activity WHERE datname=current_database() "
                "AND backend_type='autovacuum worker' "
                "AND query LIKE '%seed_autovacuum_probe%' LIMIT 1;"
            )
            if worker:
                break
            time.sleep(0.25)
        assert worker, "隔离测试必须实际观察到 autovacuum worker"
        with target.lock() as connection:
            target.assert_idle(connection)
            with psycopg.connect(
                host=target.host,
                port=target.port,
                user=target.user,
                password=target.password_file.read_text(),
                dbname=target.database,
            ):
                with pytest.raises(snapshot.SnapshotError, match="仍有连接"):
                    target.assert_idle(connection)
    finally:
        if worker:
            target.psql(f"SELECT pg_cancel_backend({int(worker)});")
        target.psql("DROP TABLE IF EXISTS seed_autovacuum_probe;")
        target.psql("ALTER SYSTEM RESET autovacuum_naptime;")
        target.psql("SELECT pg_reload_conf();")


@pytest.mark.parametrize("mode", ["archive", "absent", "skip"])
def test_other_checkout_cannot_use_interrupted_restore(workspace, tmp_path, monkeypatch, mode):
    """失败事实随共享卷保存，另一checkout不能将半库误认为普通已有库。"""
    paths, target = workspace
    monkeypatch.setattr(
        snapshot,
        "install_artifacts",
        lambda *_: (_ for _ in ()).throw(snapshot.SnapshotError("injected artifact failure")),
    )
    with pytest.raises(snapshot.SnapshotError):
        seed.initialize(paths, target=target)
    other = seed.runtime_paths(tmp_path / "另一 checkout")
    if mode == "archive":
        archive = other.root / "devdata/seed/aima_recent30.tar.gz"
        archive.parent.mkdir(parents=True)
        shutil.copy(paths.root / "devdata/seed/aima_recent30.tar.gz", archive)
    with pytest.raises(snapshot.SnapshotError, match="未完成"):
        seed.initialize(other, target=target, skip=mode == "skip")
    assert target.summary()["contents"] == 1


def test_other_checkout_cannot_pair_restored_database_with_wrong_artifacts(workspace, tmp_path):
    """成功事实也绑定Artifact根，缺少本地缓存不等于可以认领共享DB。"""
    paths, target = workspace
    seed.initialize(paths, target=target)
    other = seed.runtime_paths(tmp_path / "另一 checkout")
    with pytest.raises(snapshot.SnapshotError, match="Artifact"):
        seed.initialize(other, target=target, skip=True)


def test_startup_lease_survives_seed_return_and_blocks_reset(workspace, monkeypatch):
    """在seed返回后的确定性屏障上，第二启动/reset仍不能进入。"""
    paths, target = workspace
    monkeypatch.setattr(seed, "local_target", lambda _: target)
    with seed.startup_session(paths, target=target) as session:
        seed.initialize(paths, session=session)
        with pytest.raises(snapshot.SnapshotError, match="正在进行"):
            seed.initialize(paths, skip=True, target=target)
        with pytest.raises(snapshot.SnapshotError, match="正在进行"):
            seed.reset(paths, execute=False)
        assert target.summary()["contents"] == 1


def test_reset_recovers_missing_database_after_drop_failure(workspace, monkeypatch):
    """DROP后CREATE失败仍能通过正式reset恢复，未知重建库则不能删除。"""
    paths, target = workspace
    seed.initialize(paths, target=target)
    monkeypatch.setattr(seed, "local_target", lambda _: target)
    monkeypatch.setattr("builtins.input", lambda _: "RESET aima_ugc")
    original = seed.DatabaseTarget.psql
    failed = False

    def fail_create(self, sql, **kwargs):
        nonlocal failed
        if sql.startswith("CREATE DATABASE") and not failed:
            failed = True
            raise snapshot.SnapshotError("injected create failure")
        return original(self, sql, **kwargs)

    monkeypatch.setattr(seed.DatabaseTarget, "psql", fail_create)
    with pytest.raises(snapshot.SnapshotError, match="injected"):
        seed.reset(paths, execute=True)
    assert target.identity()["database_oid"] is None
    seed.reset(paths, execute=True)
    assert target.empty()
    assert seed.read_state(paths) is None
    assert (paths.data / "artifacts/raw/fixture.json").exists()


def test_reset_dry_run_wrong_confirmation_and_foreign_rebuild_are_safe(workspace, monkeypatch):
    """只读预览/错误确认不写；reset中断后陌生重建库不能被旧marker删除。"""
    paths, target = workspace
    seed.initialize(paths, target=target)
    monkeypatch.setattr(seed, "local_target", lambda _: target)
    before = target.read_shared_state()
    seed.reset(paths, execute=False)
    assert target.read_shared_state() == before
    monkeypatch.setattr("builtins.input", lambda _: "wrong")
    with pytest.raises(snapshot.SnapshotError, match="确认词"):
        seed.reset(paths, execute=True)
    assert target.read_shared_state() == before
    pending = {**before, "status": "resetting", "reset_phase": "drop_pending"}
    seed.persist_state(paths, target, pending)
    target.psql(f"DROP DATABASE {snapshot.quote(target.database)};", database="postgres")
    target.psql(f"CREATE DATABASE {snapshot.quote(target.database)};", database="postgres")
    target.psql("CREATE TABLE foreign_data(id int); INSERT INTO foreign_data VALUES (77);")
    monkeypatch.setattr("builtins.input", lambda _: "RESET aima_ugc")
    with pytest.raises(snapshot.SnapshotError, match="陌生"):
        seed.reset(paths, execute=True)
    assert target.psql("SELECT id FROM foreign_data;") == "77"


def test_reset_recovers_create_success_before_marker_cleanup(workspace, monkeypatch):
    """CREATE成功后清理状态失败，可识别已创建身份而不再次删库。"""
    paths, target = workspace
    seed.initialize(paths, target=target)
    monkeypatch.setattr(seed, "local_target", lambda _: target)
    monkeypatch.setattr("builtins.input", lambda _: "RESET aima_ugc")
    original = seed.DatabaseTarget.clear_shared_state
    monkeypatch.setattr(
        seed.DatabaseTarget,
        "clear_shared_state",
        lambda _: (_ for _ in ()).throw(snapshot.SnapshotError("cleanup failure")),
    )
    with pytest.raises(snapshot.SnapshotError, match="cleanup"):
        seed.reset(paths, execute=True)
    created_identity = target.identity()
    assert seed.read_state(paths)["reset_phase"] == "created"
    monkeypatch.setattr(seed.DatabaseTarget, "clear_shared_state", original)
    seed.reset(paths, execute=True)
    assert target.identity() == created_identity
    assert target.read_shared_state() is None
    assert seed.read_state(paths) is None


def test_reset_does_not_adopt_database_created_immediately_after_drop(workspace, monkeypatch):
    """DROP返回前注入陌生重建，采样不得把陌生OID认领成absent的归属。"""
    paths, target = workspace
    seed.initialize(paths, target=target)
    previous = target.identity()
    monkeypatch.setattr(seed, "local_target", lambda _: target)
    monkeypatch.setattr("builtins.input", lambda _: "RESET aima_ugc")
    original = seed.DatabaseTarget.psql
    injected = False

    def rebuild_after_drop(self, sql, **kwargs):
        nonlocal injected
        result = original(self, sql, **kwargs)
        if sql.startswith("DROP DATABASE") and not injected:
            injected = True
            original(self, f"CREATE DATABASE {snapshot.quote(self.database)};", database="postgres")
            original(
                self, "CREATE TABLE foreign_data(id int); INSERT INTO foreign_data VALUES(77);"
            )
        return result

    monkeypatch.setattr(seed.DatabaseTarget, "psql", rebuild_after_drop)
    with pytest.raises(snapshot.SnapshotError, match="陌生"):
        seed.reset(paths, execute=True)
    assert target.read_shared_state()["identity"] == previous
    with pytest.raises(snapshot.SnapshotError, match="陌生"):
        seed.reset(paths, execute=True)
    assert target.psql("SELECT id FROM foreign_data;") == "77"
